name: Deploy Angular Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Build Angular app
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          OWNER_NAME="${GITHUB_REPOSITORY_OWNER}"

          if [ "$REPO_NAME" = "$OWNER_NAME.github.io" ]; then
            BASE_HREF="/"
          else
            BASE_HREF="/$REPO_NAME/"
          fi

          npm run build -- --base-href "$BASE_HREF"
          touch dist/angular-profile-cv-style-portfolio/browser/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/angular-profile-cv-style-portfolio/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
